### PR TITLE
Support Short Position

### PR DESCRIPTION
**Pull request by aumanusorn**
add column for short position in base page
add row for short position in position page
edit blueprint to support short position
bug fix

### CODE REVIEW

**Comment by terry3041** [comment]
500 Internal Server Error when accessing the /positions page
```
[2022-03-23 14:25:55,065] ERROR in app: Exception on /positions [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/futuresboard/blueprint.py", line 652, in positions_page
    return render_template(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/futuresboard/templates/positions.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ubuntu/.local/lib/python3.8/site-packages/futuresboard/templates/base.html", line 113, in top-level template code
    <div id="content">{% block content %}{% endblock %}</div>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/futuresboard/templates/positions.html", line 51, in block 'content'
    <td>{{ positions[coin][0][1][5]}} {{ positions[coin][0][1][3] }}x</td>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: list object has no element 1
```

**Comment by aumanusorn** [comment]
Please verify my code again. Thank you
@ecoppen

**Comment by ecoppen** [comment]
Looks good to me although when @terry3041 ran it last time it picked up an error - hopefully they can verify also!

**Comment by aumanusorn** [comment]
Good! I'm not sure he already updated Blueprint.py also before testing.

**Comment by terry3041** [comment]
Looks good to me now!
@aumanusorn tysm

**Pull request merged**
